version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o}
      - GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.0-flash}
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-3-7-sonnet-max}
      - BATTLE_VERIFIER_HOST=${BATTLE_VERIFIER_HOST:-localhost}
      - BATTLE_VERIFIER_PORT=${BATTLE_VERIFIER_PORT:-3000}
      - BATTLE_VERIFIER_PROTOCOL=${BATTLE_VERIFIER_PROTOCOL:-http}
    volumes:
      - ./app:/app/app
    restart: unless-stopped 